/* 

GLOBAL 
LOCAL

- O ESCOPO DETERMINA A VIISIBILIDADE DE UMA VARIÁVEL 
 
- AS FUNÇÕES NO JS CRIAM O SEU PRÓPRIO ESCOPO
    - AS VARIÁVEIS DE UMA FUNÇÃO NÃO SÃO ACESSIVEIS FORA DELA 

- O ESCOPO DA FUNÇÃO É AS CHAVES {}
A VARIÁVEL SÓ EXISTE DENTRO DO ESCOPO DA FUNÇÃO
SE A VARIÁVEL NÃO FOSSE DECLARADA COM VAR, LET, CONST, ELA SERIA GLOBAL MESMO DENTRO DO ESCOPO
PORÉM É UMA MÁ PRÁTICA FAZER DESSA FORMA

SE A VARIÁVEL TIVER FORA DE CHAVES, ELA SEMPRE SERÁ GLOBAL


*/


function teste(){
    let a = 123
    console.log(a)
}

teste()